- hosts: localhost
  connection: local
  
  tasks:
  - name: Create & Start Container
    docker_container:
      name: myweb
      image: "ghcr.io/c1t1d0s7/jenkins-ansible-agent:{{ lookup('env','BUILD_NUMBER') }}"
      state: started
      ports:
      - "80:8080"
